# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0006_auto_20180613_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard_details',
            old_name='emp_email',
            new_name='empname_name',
        ),
        migrations.RenameField(
            model_name='dashboard_details',
            old_name='emp_name',
            new_name='empployee_email',
        ),
        migrations.RenameField(
            model_name='dashboard_details',
            old_name='emp_id',
            new_name='empployee_id',
        ),
        migrations.RenameField(
            model_name='dashboard_details',
            old_name='emp_team',
            new_name='team',
        ),
    ]
