# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0008_auto_20180613_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='dashboard_details',
            old_name='empployee_id',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='dashboard_details',
            old_name='empname_name',
            new_name='employee_name',
        ),
    ]
