# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_auto_20180613_1548'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboard_details',
            table=None,
        ),
    ]
