# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0014_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_details',
            name='production_count',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
