# Generated by Django 2.0.6 on 2018-06-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credentials',
            table='credentials',
        ),
    ]
