# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_login_cred'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_email', models.CharField(max_length=20)),
                ('emp_team', models.CharField(max_length=20)),
            ],
        ),
    ]
