# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0005_dashboard_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboard_details',
            table='empdetails',
        ),
        migrations.AlterModelTable(
            name='login_cred',
            table='logincred',
        ),
    ]
