# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0012_auto_20180614_1551'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboard_details',
            table=None,
        ),
    ]
