# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='emlopyee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_id', models.TextField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
            ],
        ),
    ]
