# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-13 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180613_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emlopyee_details',
            new_name='employee',
        ),
    ]
