# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20180613_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
                ('employee_email', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employeedetails',
            },
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
