# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20180618_1050'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboard_details',
            table=None,
        ),
    ]
