# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20180612_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mail_id',
            field=models.EmailField(max_length=254),
        ),
    ]
